// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckpointTask(arg1) {
  return window['go']['main']['App']['CheckpointTask'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAssetFolders() {
  return window['go']['main']['App']['GetAssetFolders']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSetupState() {
  return window['go']['main']['App']['GetSetupState']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PreviewTask(arg1) {
  return window['go']['main']['App']['PreviewTask'](arg1);
}

export function QuitTask(arg1) {
  return window['go']['main']['App']['QuitTask'](arg1);
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function RunBenchmark(arg1) {
  return window['go']['main']['App']['RunBenchmark'](arg1);
}

export function ScanAssets() {
  return window['go']['main']['App']['ScanAssets']();
}

export function SelectHashcatBinary() {
  return window['go']['main']['App']['SelectHashcatBinary']();
}

export function SelectHashcatDirectory() {
  return window['go']['main']['App']['SelectHashcatDirectory']();
}

export function SkipTask(arg1) {
  return window['go']['main']['App']['SkipTask'](arg1);
}

export function StartHashcatDownload() {
  return window['go']['main']['App']['StartHashcatDownload']();
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UseSystemHashcat() {
  return window['go']['main']['App']['UseSystemHashcat']();
}

export function ValidateHashcatBinary(arg1) {
  return window['go']['main']['App']['ValidateHashcatBinary'](arg1);
}
