// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hashcat} from '../models';
import {main} from '../models';
import {settings} from '../models';
import {tasks} from '../models';

export function CheckpointTask(arg1:string):Promise<void>;

export function CreateRawTask(arg1:string):Promise<string>;

export function CreateTask(arg1:hashcat.HashcatArgs):Promise<string>;

export function DeleteTask(arg1:string):Promise<void>;

export function DownloadHashesComEscrowJobHashes(arg1:number,arg2:string):Promise<string>;

export function GetAssetFolders():Promise<main.AssetFolders>;

export function GetDevices():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetSetupState():Promise<main.SetupState>;

export function ListHashesComEscrowJobs():Promise<main.HashesComEscrowJobsResult>;

export function ListTasks():Promise<Array<tasks.TaskInfo>>;

export function PauseTask(arg1:string):Promise<void>;

export function PreviewRawTask(arg1:string):Promise<Array<string>>;

export function PreviewTask(arg1:hashcat.HashcatArgs):Promise<Array<string>>;

export function QuitTask(arg1:string):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function RunBenchmark(arg1:number):Promise<string>;

export function RunBenchmarkWithOptions(arg1:number,arg2:hashcat.BenchmarkOptions):Promise<string>;

export function ScanAssets():Promise<main.ScannedAssets>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectHashcatBinary():Promise<main.SetupState>;

export function SelectHashcatDirectory():Promise<main.SetupState>;

export function SkipTask(arg1:string):Promise<void>;

export function StartHashcatDownload():Promise<void>;

export function StartTask(arg1:string):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;

export function UseSystemHashcat():Promise<main.SetupState>;

export function ValidateHashcatBinary(arg1:string):Promise<hashcat.HashcatBinaryInfo>;
